## Preprocessing

In [3]:
! pip install tensorflow

Collecting tensorflow
  Downloading tensorflow-2.14.0-cp39-cp39-macosx_10_15_x86_64.whl (229.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.6/229.6 MB 9.1 MB/s eta 0:00:0000:0100:01
Collecting absl-py>=1.0.0 (from tensorflow)
  Downloading absl_py-2.0.0-py3-none-any.whl (130 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 4.7 MB/s eta 0:00:00
Collecting astunparse>=1.6.0 (from tensorflow)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting flatbuffers>=23.5.26 (from tensorflow)
  Downloading flatbuffers-23.5.26-py2.py3-none-any.whl (26 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Downloading gast-0.5.4-py3-none-any.whl (19 kB)
Collecting google-pasta>=0.1.1 (from tensorflow)
  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 1.8 MB/s eta 0:00:00
Requirement already satisfied: h5py>=2.9.0 in /Users/mariakouiderelouahed/opt/anaconda3/lib/python3.9/site-packages (from tensorflow) (3.7.0)
Collecting libclang>=13.0.0 (from tensorflow)
  Downloading libclang-16.0.6-py2.py3-none-macosx_10_9_x86_64.whl (24.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 38.4 MB/s eta 0:00:0000:0100:01
Collecting ml-dtypes==0.2.0 (from tensorflow)
  Downloading ml_dtypes-0.2.0-cp39-cp39-macosx_10_9_universal2.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 27.8 MB/s eta 0:00:0000:01
Requirement already satisfied: numpy>=1.23.5 in /Users/mariakouiderelouahed/opt/anaconda3/lib/python3.9/site-packages (from tensorflow) (1.24.3)
Collecting opt-einsum>=2.3.2 (from tensorflow)
  Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 2.4 MB/s eta 0:00:00
Requirement already satisfied: packaging in /Users/mariakouiderelouahed/opt/anaconda3/lib/python3.9/site-packages (from tensorflow) (23.0)
Collecting protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 (from tensorflow)
  Downloading protobuf-4.25.0-cp37-abi3-macosx_10_9_universal2.whl (393 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 393.9/393.9 kB 12.0 MB/s eta 0:00:00
Requirement already satisfied: setuptools in /Users/mariakouiderelouahed/opt/anaconda3/lib/python3.9/site-packages (from tensorflow) (67.8.0)
Requirement already satisfied: six>=1.12.0 in /Users/mariakouiderelouahed/opt/anaconda3/lib/python3.9/site-packages (from tensorflow) (1.16.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Downloading termcolor-2.3.0-py3-none-any.whl (6.9 kB)
Requirement already satisfied: typing-extensions>=3.6.6 in /Users/mariakouiderelouahed/opt/anaconda3/lib/python3.9/site-packages (from tensorflow) (4.6.3)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in /Users/mariakouiderelouahed/opt/anaconda3/lib/python3.9/site-packages (from tensorflow) (1.14.1)
Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow)
  Downloading tensorflow_io_gcs_filesystem-0.34.0-cp39-cp39-macosx_10_14_x86_64.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 32.6 MB/s eta 0:00:0000:01
Collecting grpcio<2.0,>=1.24.3 (from tensorflow)
  Downloading grpcio-1.59.2-cp39-cp39-macosx_10_10_universal2.whl (9.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 53.2 MB/s eta 0:00:0000:0100:01
Collecting tensorboard<2.15,>=2.14 (from tensorflow)
  Downloading tensorboard-2.14.1-py3-none-any.whl (5.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 52.4 MB/s eta 0:00:0000:0100:01
Collecting tensorflow-estimator<2.15,>=2.14.0 (from tensorflow)
  Downloading tensorflow_estimator-2.14.0-py2.py3-none-any.whl (440 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.7/440.7 kB 14.7 MB/s eta 0:00:00
Collecting keras<2.15,>=2.14.0 (from tensorflow)
  Downloading keras-2.14.0-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 34.6 MB/s eta 0:00:0000:01
Requirement already satisfied: wheel<1.0,>=0.23.0 in /Users/mariakouiderelouahed/opt/anaconda3/lib/python3.9/site-packages (from astunparse>=1.6.0->tensorflow) (0.38.4)
Collecting google-auth<3,>=1.6.3 (from tensorboard<2.15,>=2.14->tensorflow)
  Downloading google_auth-2.23.4-py2.py3-none-any.whl (183 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.3/183.3 kB 6.9 MB/s eta 0:00:00
Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.15,>=2.14->tensorflow)
  Downloading google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: markdown>=2.6.8 in /Users/mariakouiderelouahed/opt/anaconda3/lib/python3.9/site-packages (from tensorboard<2.15,>=2.14->tensorflow) (3.4.1)
Requirement already satisfied: requests<3,>=2.21.0 in /Users/mariakouiderelouahed/opt/anaconda3/lib/python3.9/site-packages (from tensorboard<2.15,>=2.14->tensorflow) (2.29.0)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.15,>=2.14->tensorflow)
  Downloading tensorboard_data_server-0.7.2-py3-none-macosx_10_9_x86_64.whl (4.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 46.9 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: werkzeug>=1.0.1 in /Users/mariakouiderelouahed/opt/anaconda3/lib/python3.9/site-packages (from tensorboard<2.15,>=2.14->tensorflow) (2.2.3)
Collecting cachetools<6.0,>=2.0.0 (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow)
  Downloading cachetools-5.3.2-py3-none-any.whl (9.3 kB)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/mariakouiderelouahed/opt/anaconda3/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow) (0.2.8)
Collecting rsa<5,>=3.1.4 (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow)
  Downloading rsa-4.9-py3-none-any.whl (34 kB)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.15,>=2.14->tensorflow)
  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: importlib-metadata>=4.4 in /Users/mariakouiderelouahed/opt/anaconda3/lib/python3.9/site-packages (from markdown>=2.6.8->tensorboard<2.15,>=2.14->tensorflow) (6.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/mariakouiderelouahed/opt/anaconda3/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/mariakouiderelouahed/opt/anaconda3/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/mariakouiderelouahed/opt/anaconda3/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /Users/mariakouiderelouahed/opt/anaconda3/lib/python3.9/site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow) (2023.5.7)
Requirement already satisfied: MarkupSafe>=2.1.1 in /Users/mariakouiderelouahed/opt/anaconda3/lib/python3.9/site-packages (from werkzeug>=1.0.1->tensorboard<2.15,>=2.14->tensorflow) (2.1.1)
Requirement already satisfied: zipp>=0.5 in /Users/mariakouiderelouahed/opt/anaconda3/lib/python3.9/site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<2.15,>=2.14->tensorflow) (3.11.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /Users/mariakouiderelouahed/opt/anaconda3/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow) (0.4.8)

Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.15,>=2.14->tensorflow)
  Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.7/151.7 kB 5.1 MB/s eta 0:00:00
Installing collected packages: libclang, flatbuffers, termcolor, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, rsa, protobuf, opt-einsum, oauthlib, ml-dtypes, keras, grpcio, google-pasta, gast, cachetools, astunparse, absl-py, requests-oauthlib, google-auth, google-auth-oauthlib, tensorboard, tensorflow
Successfully installed absl-py-2.0.0 astunparse-1.6.3 cachetools-5.3.2 flatbuffers-23.5.26 gast-0.5.4 google-auth-2.23.4 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 grpcio-1.59.2 keras-2.14.0 libclang-16.0.6 ml-dtypes-0.2.0 oauthlib-3.2.2 opt-einsum-3.3.0 protobuf-4.25.0 requests-oauthlib-1.3.1 rsa-4.9 tensorboard-2.14.1 tensorboard-data-server-0.7.2 tensorflow-2.14.0 tensorflow-estimator-2.14.0 tensorflow-io-gcs-filesystem-0.34.0 termcolor-2.3.0

In [6]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

2023-11-13 22:12:46.429151: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [7]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN', 'NAME'])
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [8]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [9]:
# Look at APPLICATION_TYPE value counts for binning
type_counts = application_df['APPLICATION_TYPE'].value_counts()
type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [10]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(type_counts.iloc[8:].index)
cutoff_value = 500

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [11]:
# Look at CLASSIFICATION value counts for binning
classification = application_df['CLASSIFICATION'].value_counts()
classification

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [12]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classifications_1= classification.loc[classification > 1]
classifications_1

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [35]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification.iloc[5:].index)
cutoff_value_classifications = 150

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [36]:
# Convert categorical data to numeric with `pd.get_dummies`
dummies_df = pd.get_dummies(application_df)
dummies_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [37]:
# Split our preprocessed data into our features and target arrays
y = dummies_df['IS_SUCCESSFUL'].values
X = dummies_df.drop(columns='IS_SUCCESSFUL').values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [38]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [39]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

input_features_total = len(X_train[0])
hidden_nodes_layer1 = 7
hidden_nodes_layer2 = 9

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim = input_features_total, activation = "relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation = "relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 7)                 308

 dense_10 (Dense)            (None, 9)                 72

 dense_11 (Dense)            (None, 1)                 10

=================================================================
Total params: 390 (1.52 KB)
Trainable params: 390 (1.52 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [40]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [41]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 1ms/step - loss: 0.6063 - accuracy: 0.6903
Epoch 2/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5662 - accuracy: 0.7237
Epoch 3/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5608 - accuracy: 0.7271
Epoch 4/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5580 - accuracy: 0.7274
Epoch 5/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5565 - accuracy: 0.7282
Epoch 6/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5557 - accuracy: 0.7282
Epoch 7/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5551 - accuracy: 0.7282
Epoch 8/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5541 - accuracy: 0.7291
Epoch 9/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5539 - accuracy: 0.7285
Epoch 10/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5535 - accuracy: 0.7296
Epoch 11/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5531 - accuracy: 0.7295
Epoch 12/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5528 - accuracy: 0.7294
Epoch 13/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5524 - accuracy: 0.7310
Epoch 14/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5521 - accuracy: 0.7295
Epoch 15/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5521 - accuracy: 0.7302
Epoch 16/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5518 - accuracy: 0.7298
Epoch 17/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5517 - accuracy: 0.7300
Epoch 18/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5516 - accuracy: 0.7303
Epoch 19/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5517 - accuracy: 0.7300
Epoch 20/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5511 - accuracy: 0.7310
Epoch 21/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5511 - accuracy: 0.7303
Epoch 22/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5511 - accuracy: 0.7295
Epoch 23/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5508 - accuracy: 0.7296
Epoch 24/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5505 - accuracy: 0.7303
Epoch 25/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5504 - accuracy: 0.7313
Epoch 26/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5504 - accuracy: 0.7306
Epoch 27/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5501 - accuracy: 0.7304
Epoch 28/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5500 - accuracy: 0.7307
Epoch 29/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5499 - accuracy: 0.7309
Epoch 30/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5498 - accuracy: 0.7316
Epoch 31/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5499 - accuracy: 0.7309
Epoch 32/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5497 - accuracy: 0.7310
Epoch 33/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5497 - accuracy: 0.7308
Epoch 34/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5493 - accuracy: 0.7311
Epoch 35/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5494 - accuracy: 0.7311
Epoch 36/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5495 - accuracy: 0.7303
Epoch 37/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5492 - accuracy: 0.7309
Epoch 38/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5495 - accuracy: 0.7317
Epoch 39/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5491 - accuracy: 0.7302
Epoch 40/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5490 - accuracy: 0.7315
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5489 - accuracy: 0.7312
Epoch 42/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5490 - accuracy: 0.7302
Epoch 43/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5488 - accuracy: 0.7313
Epoch 44/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5490 - accuracy: 0.7312
Epoch 45/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5489 - accuracy: 0.7317
Epoch 46/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5487 - accuracy: 0.7315
Epoch 47/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5486 - accuracy: 0.7311
Epoch 48/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5489 - accuracy: 0.7315
Epoch 49/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5485 - accuracy: 0.7316
Epoch 50/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5488 - accuracy: 0.7320
Epoch 51/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5485 - accuracy: 0.7320
Epoch 52/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5485 - accuracy: 0.7319
Epoch 53/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5484 - accuracy: 0.7311
Epoch 54/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5484 - accuracy: 0.7311
Epoch 55/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5483 - accuracy: 0.7315
Epoch 56/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5485 - accuracy: 0.7305
Epoch 57/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5484 - accuracy: 0.7313
Epoch 58/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5482 - accuracy: 0.7320
Epoch 59/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5485 - accuracy: 0.7317
Epoch 60/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5484 - accuracy: 0.7314
Epoch 61/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5482 - accuracy: 0.7317
Epoch 62/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5483 - accuracy: 0.7315
Epoch 63/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5482 - accuracy: 0.7318
Epoch 64/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5481 - accuracy: 0.7314
Epoch 65/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5480 - accuracy: 0.7310
Epoch 66/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5482 - accuracy: 0.7324
Epoch 67/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5480 - accuracy: 0.7311
Epoch 68/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5482 - accuracy: 0.7309
Epoch 69/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5481 - accuracy: 0.7313
Epoch 70/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5481 - accuracy: 0.7317
Epoch 71/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5479 - accuracy: 0.7313
Epoch 72/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5480 - accuracy: 0.7317
Epoch 73/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5478 - accuracy: 0.7320
Epoch 74/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5477 - accuracy: 0.7325
Epoch 75/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5479 - accuracy: 0.7318
Epoch 76/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5478 - accuracy: 0.7311
Epoch 77/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5479 - accuracy: 0.7320
Epoch 78/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5481 - accuracy: 0.7322
Epoch 79/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5478 - accuracy: 0.7315
Epoch 80/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5477 - accuracy: 0.7326
Epoch 81/100

804/804 [==============================] - 1s 1ms/step - loss: 0.5478 - accuracy: 0.7312
Epoch 82/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5477 - accuracy: 0.7322
Epoch 83/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5477 - accuracy: 0.7313
Epoch 84/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5478 - accuracy: 0.7317
Epoch 85/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5477 - accuracy: 0.7318
Epoch 86/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5476 - accuracy: 0.7320
Epoch 87/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5475 - accuracy: 0.7312
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7313
Epoch 89/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5476 - accuracy: 0.7313
Epoch 90/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5476 - accuracy: 0.7321
Epoch 91/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5477 - accuracy: 0.7315
Epoch 92/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5474 - accuracy: 0.7318
Epoch 93/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5474 - accuracy: 0.7318
Epoch 94/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5473 - accuracy: 0.7324
Epoch 95/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5475 - accuracy: 0.7311
Epoch 96/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5473 - accuracy: 0.7327
Epoch 97/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5474 - accuracy: 0.7322
Epoch 98/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5475 - accuracy: 0.7319
Epoch 99/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5475 - accuracy: 0.7315
Epoch 100/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5473 - accuracy: 0.7313

In [42]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=0)
print(f"Model Loss: {model_loss}, Model Accuracy: {model_accuracy}")

Model Loss: 0.5521423816680908, Model Accuracy: 0.72967928647995

In [43]:
# Export our model to HDF5 file
filepath = r"/Users/mariakouiderelouahed/Desktop/Module 21AlphabetSoupCharity.h5"
nn.save(filepath)

/Users/mariakouiderelouahed/opt/anaconda3/lib/python3.9/site-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(